name: mangayomi
description: Free and open source manga reader and anime streaming cross-plateform app inspired by Tachiyomi and Aniyomi.
publish_to: "none"
version: 0.6.35+86

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  html: ^0.15.5
  font_awesome_flutter: ^10.8.0
  expandable_text: ^2.3.0
  flex_color_scheme: ^8.1.0
  extended_image: ^10.0.0
  photo_view: ^0.15.0
  grouped_list: ^6.0.0
  intl: 0.20.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  flutter_inappwebview: ^6.2.0-beta.2
  draggable_menu: ^4.4.1
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  share_plus: ^10.0.2
  xpath_selector_html_parser: ^3.0.1
  archive: ^4.0.1
  file_picker: ^10.0.0
  path_provider: ^2.1.5
  scrollable_positioned_list: ^0.3.8
  json_path: ^0.7.4
  bot_toast: ^4.1.3
  flutter_web_auth_2: ^3.1.2
  numberpicker: ^2.1.2
  encrypt: ^5.0.3
  media_kit: ^1.2.0
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: media_kit_video
      ref: aeb29faa8ea93a386ad1185b69fd6225fa331c74
  media_kit_libs_video: ^1.0.6
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  ffi: ^2.1.3
  ffigen: ^16.0.0
  http_interceptor: ^2.0.0
  js_packer: ^0.0.5
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: main
  http: ^1.3.0
  re_editor:
    git:
      url: https://github.com/kodjodevf/re-editor
      ref: main
  re_highlight: ^0.0.3
  json_view: ^0.4.2
  super_sliver_list: ^0.4.1
  flutter_rust_bridge: 2.10.0
  rust_lib_mangayomi:
    path: rust_builder
  pseudom: ^1.0.1
  path: ^1.9.0
  freezed_annotation: ^2.4.4
  desktop_webview_window:
    git:
      url: https://github.com/kodjodevf/desktop_webview_window.git
      path: packages/desktop_webview_window
      ref: main
  screen_brightness: ^2.1.1
  flutter_widget_from_html: ^0.16.0
  convert: ^3.1.2
  connectivity_plus: ^6.1.3
  app_links: ^6.4.0
  win32: ^5.10.1
  protobuf: ^4.0.0
  device_info_plus: ^11.3.3
  marquee: ^2.2.3
  epubx:
    git:
      url: https://github.com/kodjodevf/epubx.dart.git
      ref: dev
  d4rt: 0.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_discord_rpc_fork:
    git:
      url: https://github.com/Schnitzel5/flutter-discord-rpc.git
      ref: main

dependency_overrides:
  ffi: ^2.1.3
  analyzer: ">=5.2.0 <7.0.0"
  html: ^0.15.4
  flutter_web_auth_2:
    git:
      url: https://github.com/ThexXTURBOXx/flutter_web_auth_2.git
      ref: 3.x-without-v1
      path: flutter_web_auth_2
  analyzer_plugin: ^0.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_generator: ^2.6.3
  flutter_launcher_icons: ^0.14.3
  isar_generator: ^3.1.0+1
  flutter_lints: ^5.0.0
  freezed: ^2.0.0
  inno_bundle: ^0.9.0
  protoc_plugin: ^22.0.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/trackers_icons/
    - assets/app_icons/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icons/icon-red.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/app_icons/icon-red.png"
  macos:
    generate: true
    image_path: "assets/app_icons/icon-red.png"
inno_bundle:
  id: 6CB26FFA-E72B-42C3-91E8-594940031CA2
  publisher: kodjodevf
  name: Mangayomi
  url: https://github.com/kodjodevf/mangayomi/
  support_url: https://github.com/kodjodevf/mangayomi/
  updates_url: https://github.com/kodjodevf/mangayomi/releases/
  languages:
    - english
    - french
    - german
  admin: false
  version: 0.6.3

