name: mangayomi
description: Free and open source manga reader and anime streaming cross-plateform app inspired by Tachiyomi and Aniyomi.
publish_to: "none"
version: 0.6.75+91

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.0
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  html: ^0.15.6
  font_awesome_flutter: ^10.12.0
  flex_color_scheme: ^8.3.1
  extended_image: ^10.0.0
  photo_view: ^0.15.0
  grouped_list: ^6.0.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  flutter_inappwebview: ^6.2.0-beta.2
  draggable_menu: ^4.4.1
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  share_plus: ^12.0.1
  xpath_selector_html_parser: ^3.0.1
  archive: ^4.0.1
  file_picker: ^10.3.7
  path_provider: ^2.1.5
  scrollable_positioned_list: ^0.3.8
  bot_toast: ^4.1.3
  flutter_web_auth_2: ^4.1.0
  numberpicker: ^2.1.2
  encrypt: ^5.0.3
  media_kit:
    git:
      url: https://github.com/Schnitzel5/media-kit.git
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/Schnitzel5/media-kit.git
      path: media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Schnitzel5/media-kit.git
      path: libs/universal/media_kit_libs_video
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  ffi: ^2.1.4
  ffigen: 19.1.0
  http_interceptor: ^2.0.0
  js_packer: ^0.0.6
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: main
  http: ^1.5.0
  re_editor: ^0.8.0
  re_highlight: ^0.0.3
  json_view: ^0.4.2
  super_sliver_list: ^0.4.1
  flutter_rust_bridge: ^2.11.1
  rust_lib_mangayomi:
    path: rust_builder
  pseudom: ^1.0.1
  path: ^1.9.0
  freezed_annotation: ^3.0.0
  desktop_webview_window:
    git:
      url: https://github.com/kodjodevf/desktop_webview_window.git
      path: packages/desktop_webview_window
      ref: main
  screen_brightness: ^2.1.1
  flutter_html: ^3.0.0
  convert: ^3.1.2
  connectivity_plus: ^7.0.0
  app_links: ^7.0.0
  win32: ^5.10.1
  protobuf: ^5.0.0
  device_info_plus: ^12.2.0
  marquee: ^2.2.3
  epubx:
    git:
      url: https://github.com/kodjodevf/epubx.dart.git
      ref: dev
  d4rt: ^0.1.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_discord_rpc_fork:
    git:
      url: https://github.com/Schnitzel5/flutter-discord-rpc.git
      ref: main
  table_calendar: ^3.2.0

dependency_overrides:
  ffi: ^2.1.3
  html: ^0.15.4
  flutter_web_auth_2:
    git:
      url: https://github.com/ThexXTURBOXx/flutter_web_auth_2.git
      ref: 3.x-without-v1
      path: flutter_web_auth_2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  riverpod_generator: ^3.0.3
  flutter_launcher_icons: ^0.14.3
  isar_community_generator: ^3.3.0
  flutter_lints: ^6.0.0
  freezed: ^3.0.0
  inno_bundle: ^0.9.0
  protoc_plugin: ^23.0.0
  # hive_generator:
  #   path: plugins/hive_generator

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/trackers_icons/
    - assets/app_icons/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icons/icon-red.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/app_icons/icon-red.png"
  macos:
    generate: true
    image_path: "assets/app_icons/icon-red.png"
inno_bundle:
  id: 6CB26FFA-E72B-42C3-91E8-594940031CA2
  publisher: kodjodevf
  name: Mangayomi
  url: https://github.com/kodjodevf/mangayomi/
  support_url: https://github.com/kodjodevf/mangayomi/
  updates_url: https://github.com/kodjodevf/mangayomi/releases/
  languages:
    - english
    - french
    - german
  admin: false
