name: mangayomi
description: Free and open source manga reader and anime streaming cross-plateform app inspired by Tachiyomi and Aniyomi.
publish_to: "none"
version: 0.2.45+57

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.2
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.3
  html: ^0.15.4
  font_awesome_flutter: ^10.6.0
  expandable_text: ^2.3.0
  flex_color_scheme: ^7.3.1
  extended_image: ^8.2.0
  photo_view: ^0.15.0
  grouped_list: ^5.1.2
  intl: ^0.19.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4
  package_info_plus: ^8.0.0
  permission_handler: ^11.2.0
  flutter_inappwebview: ^5.8.0
  draggable_menu: ^4.4.1
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  share_plus: ^9.0.0
  xpath_selector_html_parser: ^3.0.1
  desktop_webview_window:
    path: ./packages/desktop_webview_window
  archive: ^3.4.10
  file_picker: ^8.0.3
  path_provider: ^2.1.2
  scrollable_positioned_list: ^0.3.8
  dart_eval: ^0.7.9
  json_path: ^0.7.0
  bot_toast: ^4.1.3
  flutter_web_auth_2: ^3.1.1
  numberpicker: ^2.1.2
  encrypt: ^5.0.3
  media_kit: ^1.1.10+1
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: media_kit_video
      ref: 0ab6b10ea660ead8e8e1694517aabe3582f25d5c
  media_kit_libs_video: ^1.0.4
  crypto: ^3.0.3
  protobuf: ^3.1.0
  cupertino_icons: ^1.0.6
  window_manager: ^0.3.8
  ffi: ^2.1.1
  ffigen: ^12.0.0
  http_interceptor: ^2.0.0-beta.8
  js_packer: ^0.0.5
  flutter_windows_webview:
    git:
      url: https://github.com/wgh136/flutter_windows_webview
      ref: master
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: main
  cronet_http:
    git:
      url: https://github.com/dart-lang/http.git
      path: pkgs/cronet_http
      ref: a2e241ba1a8fdf22ce17e047ab6af8f46787faf8
  cupertino_http: ^1.5.0
  http: ^1.2.1
  flutter_code_editor: ^0.3.1
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  json_view: ^0.4.2
  super_sliver_list: ^0.4.1

dependency_overrides:
  http: ^1.2.1
  ffi: ^2.1.2
  flex_seed_scheme: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  isar_generator: ^3.1.0+1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/trackers_icons/
    - assets/app_icons/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icons/icon-red.png"
  min_sdk_android: 24
  windows:
    generate: true
    image_path: "assets/app_icons/icon-red.png"
  macos:
    generate: true
    image_path: "assets/app_icons/icon-red.png"
