blank_issues_enabled: false
contact_links:
  - name: âš ï¸ Extension Issue
      url: https://github.com/kodjodevf/mangayomi-extensions/issues/new/choose
      about: Issues and requests for extensions and sources should be opened in the mangayomi-extensions repository instead
  - name: ğŸ§‘â€ğŸ’» Mangayomi help discord
    url: https://discord.com/invite/EjfBuYahsP
    about: Common questions are answered here
