[package]
name = "rust_lib_mangayomi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "=2.4.0", features = ["chrono"] }
image = "0.25.0"
chrono = "0.4.38"
futures-util = "0.3.30"
reqwest = { version = "0.12.7", default-features = false, features = ["charset", "http2", "rustls-tls", "rustls-tls-native-roots", "stream", "multipart"] }
tokio = { version = "1.39.3", features = ["full"] }
tokio-util = "0.7.11"
